[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle domain specific redirects
[[redirects]]
  from = "https://stunews.static.domains/callback*"
  to = "/redirect-from-external"
  status = 200
  force = true

# Handle other redirects
[[redirects]]
  from = "/api/auth/google-callback*"
  to = "/callback"
  status = 200
  force = true 